// src/lib/og.svelte
<script lang="ts">
	export let title: string = 'MerginIT e.U.';
	export let subtitle: string = 'Professional Software Development & SaaS Solutions';
	export let image: string | undefined = undefined;
</script>

<div
	style="
		height: 100%;
		width: 100%;
		display: flex;
		text-align: center;
		align-items: center;
		justify-content: center;
		flex-direction: column;
		flex-wrap: nowrap;
		background-color: #f0f0f0;
		font-family: 'Noto Sans', sans-serif;
	"
>
	<div style="display: flex; align-items: center; justify-content: center;">
		<img
			src={image ?? 'https://merginit.com/favicon.png'}
			alt="MerginIT Logo"
			style="margin: 0 40px; width: 120px; height: 120px;"
		/>
	</div>
	<div
		style="
			display: flex;
			font-size: 48px;
			font-style: normal;
			color: black;
			margin-top: 30px;
			line-height: 1.2;
			white-space: pre-wrap;
			font-weight: bold;
		"
	>
		{title || 'MerginIT e.U.'}
	</div>
	<div
		style="
			display: flex;
			font-size: 24px;
			font-style: normal;
			color: #666;
			margin-top: 20px;
			line-height: 1.4;
			white-space: pre-wrap;
			text-align: center;
		"
	>
		{subtitle || 'Professional Software Development & SaaS Solutions'}
	</div>
</div>

// static/og.jsx
<div
  style={{
    height: '100%',
    width: '100%',
    display: 'flex',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    flexWrap: 'nowrap',
    backgroundColor: '#f0f0f0',
    backgroundImage: `url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg"%3E%3Cdefs%3E%3Cpattern id="a" width="29" height="50.115" patternTransform="rotate(20)scale(2)" patternUnits="userSpaceOnUse"%3E%3Crect width="100%25" height="100%25" fill="%23f0f0f0"/%3E%3Cpath fill="none" stroke="%23f5d800" stroke-width="1.5" d="M14.498 16.858 0 8.488.002-8.257l14.5-8.374L29-8.26l-.002 16.745zm0 50.06L0 58.548l.002-16.745 14.5-8.373L29 41.8l-.002 16.744zM28.996 41.8l-14.498-8.37.002-16.744L29 8.312l14.498 8.37-.002 16.745zm-29 0-14.498-8.37.002-16.744L0 8.312l14.498 8.37-.002 16.745z"/%3E%3C/pattern%3E%3C/defs%3E%3Crect width="800%25" height="800%25" fill="url(%23a)" transform="translate(-12)"/%3E%3C/svg%3E');`
}}
>
  <div
    style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    }}
  >
    <img
      src="https://merginit.com/favicon.png"
      alt="MerginIT Logo"
      width={120}
      height={120}
      style={{ margin: '0 40px' }}
    />
  </div>
  <div
    style={{
      display: 'flex',
      fontSize: 48,
      fontStyle: 'normal',
      color: 'black',
      marginTop: 30,
      lineHeight: 1.2,
      whiteSpace: 'pre-wrap',
      fontWeight: 'bold',
    }}
  >
    <b>MerginIT e.U.</b>
  </div>
  <div
    style={{
      display: 'flex',
      fontSize: 24,
      fontStyle: 'normal',
      color: '#666',
      marginTop: 20,
      lineHeight: 1.4,
      whiteSpace: 'pre-wrap',
      textAlign: 'center',
    }}
  >
    Professional Software Development & SaaS Solutions
  </div>
</div>

/* https://og-playground.vercel.app/?share=rVVbb9MwFP4rltEoE23ipGmXhouEBhKTNoHUTbz0ATdxUoNjR467bKv23znOtR1sEwj1ocffuebzOcc7HKuE4Qi_Tfj1SiJUmlvB3u12VkZow3i2MREaeYQcjcYNWPHEbB5gCS8LQW8BTQW76VDDbswHwTMJeMykYbrTUIueGZaXv6l-bEvD09tTBaC0uQ_VNv5HrllsuKrjKrHN5b72m6YFKKSqQOgUaxr_zLTayuRUCaVB_yIl9ve7wVlOMxah71stXo0SamjELeKW19nrm1yMj6anICIQZfluhTfGFJHrVlXlVFNH6cz1CSHWeoWPpp_AOmFp2UgFNfApEvEEHOkKN1yC7C_g0LANpxlxPG8GSGt_qaksU6Vz0GllqGGvfHJcxlSAcDzYXUlubEnbkullQWP2RV6VrCvDctYntJfn2xR90h5JuRBwPvKnDUMr7PbVbzqtVBICQ7to9ZO11rMkJGDdgpM-lWOj2i--8AInWITImzvhLEQEhU4Qhg4h_iR0_NmJAP0MxOlJcO4vLDYXE6u2HifB7C4nCLgh83P4D51ZEIraudGi3nsK3ijwnHDfO7i78ENnsZi3mqaW2n4IYvNCVVPPt7XYWq3-sIYJmJDH3O03PeXdk-m2d9aehh45uCYg9ME19Uh7EbZLgXxq28Ds9UktC9sqE8_2SJcW-hKk0fGb7yt5f7-S7237d9P_cP4fG-wnB_jZEbZpEaoTQ2qeZ51fqeN2oEqYqJzpjENHO7HK3ZRe81hJp5AwVkMRlpGL2u7sEp2rTA3KhsKd55M63bDODrHug1FObRgolqCAFDejtkyE3IYiFzj6R7JSIGLJ72CpBOEhaAPUu0rnVAwOsNTqHbUWsJUGuCnxUsF6m5IeFVyyz-2i9hy_x6sNN6xeAxCp0DCQe_uwyf-t2-9rJZI_X8_6fc8vc66ct-76P9LhB39Fx4v5fP5HNvzH2BjiP8PG40_VAR1ftUpZWcLTQwVaqtRUVDP0kV0zoYoc_NBLtKR0CTqxtS9UuU9W84_HWBW1Dkc7XLcpjmCsx7jpTxwF9pCw9TbDUUpFycaY5eoHv7wt7FttqvoEcSxpn_I1S3Bk9Jbdj7Gha7DYMCFUpbRI8P0v */
